<?php
$produto = $this->view->getProduto;
?>

<link href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<link rel="stylesheet" href="/css/login.css">
<script src="/js/produto.js"></script>

<div class="container mt-4 mb-4 produto-container">
    <div class="row">
        <div class="col-xs-12 mb-4">
            <div class="form-wrap">
                <h1 class="text-primary text-center">Criar um produto</h1>
                <br>
                <div class="form-group col-xs-6">
                    <label for="nome">Nome</label>
                    <input value="<?= isset($produto['nome']) ? $produto['nome'] : '' ?>" id="nome" type="text" name="nome" class="form-control" placeholder="name">
                </div>
                <div class="form-group col-xs-6">
                    <label for="preco">Preço</label>
                    <input value="<?= isset($produto['preco']) ? $produto['preco'] : '' ?>" id="preco" name="preco" class="form-control" placeholder="Preço">
                </div>
                <div class="form-group col-xs-6">
                    <label>Descricao:</label>
                    <input value="<?= isset($produto['descricao']) ? $produto['descricao'] : '' ?>" id="descricao" type="text" name="descricao" class="form-control" placeholder="Descricao">
                </div>
                <div class="form-group col-xs-6 d-flex flex-row">
                    <input style="display: none;" id="img" type="file" name="img">
                    <label>Imagem Principal:</label>
                    <button id="imgAlterado" class="btn btn-primary"> Escolher Arquivo</button>
                    <input type="text" class="form-control ml-2" placeholder="Imagem" id="inputImgAlterado">
                </div>
                <div class="form-group col-xs-12 text-center">
                    <h4>Imagem Opcionais:</h4>
                </div>
                <div class="form-group col-xs-4 d-flex flex-row">
                    <input style="display: none;" id="img2" type="file" name="img2">
                    <label>Imagem 2:</label>
                    <button id="imgAlterado2" class="btn btn-primary ml-1"> Escolher Arquivo</button>
                    <input type="text" class="form-control ml-2" placeholder="Imagem" id="inputImgAlterado2">
                </div>
                <div class="form-group col-xs-4 d-flex flex-row">
                    <input style="display: none;" id="img3" type="file" name="img3">
                    <label>Imagem 3:</label>
                    <button id="imgAlterado3" class="btn btn-primary ml-1"> Escolher Arquivo</button>
                    <input type="text" class="form-control ml-2" placeholder="Imagem" id="inputImgAlterado3">
                </div>
                <div class="form-group col-xs-4 d-flex flex-row">
                    <input style="display: none;" id="img4" type="file" name="img4">
                    <label>Imagem 4:</label>
                    <button id="imgAlterado4" class="btn btn-primary ml-1"> Escolher Arquivo</button>
                    <input type="text" class="form-control ml-2" placeholder="Imagem" id="inputImgAlterado4">
                </div>
                <div class="form-group col-xs-12  text-center mt-2">
                    <button onclick="criarProduto()" type="button" id="btn-login" class="btn btn-custom btn-success btn-lg">Criar</button>
                    <a class="btn btn-custom btn-primary btn-lg" href="/listagemProdutoAdmin">Voltar</a>
                </div>
            </div>
        </div>
    </div>
</div>