<?php
$produtos = $this->view->getProdutos;

$valorUmEncontrado = false;
$valorDoisEncontrado = false;
$valorTresEncontrado = false;

// Percorre cada sub-array
foreach ($this->view->getProdutosRecomendados as $subArray) {
    // Verifica se o valor "1" está presente no sub-array atual
    if (in_array('1', $subArray)) {
        $valorUmEncontrado = true;
    }
    // Verifica se o valor "2" está presente no sub-array atual
    if (in_array('2', $subArray)) {
        $valorDoisEncontrado = true;
    }
    // Verifica se o valor "3" está presente no sub-array atual
    if (in_array('3', $subArray)) {
        $valorTresEncontrado = true;
    }
}
?>

<link href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<link rel="stylesheet" href="/css/all.css">
<script src="/js/produto.js"></script>
<?php if (count($this->view->getProdutosRecomendados) < 3) { ?>
<div id="cadastrar-produto-recomendado-sucesso" class="mt-5"></div>
<div class="container mt-4 mb-4 produto-container">
    <div class="row">
        <div class="col-xs-12 mb-4">
            <div class="form-wrap">
                <h1 class="text-primary text-center">Criar um produto Recomendado</h1>
                <br>
                <div class="form-group col-xs-6">
                    <label for="preco">Produto</label>
                    <select id="produto_id" name="produto_id" class="form-control" id="exampleFormControlSelect1">
                        <option value="">Selecione</option>
                        <?php foreach ($produtos as $produto) { ?>
                            <option value="<?=$produto['id']?>"><?=$produto['nome']?></option>
                        <?php } ?>
                    </select>
                </div>
                <div class="form-group col-xs-6">
                    <label for="preco">Numero Sequencia</label>
                    <select id="numero_sequencia" name="numero_sequencia" class="form-control" id="exampleFormControlSelect1">
                    <?php if (!$valorUmEncontrado) { ?>
                                <option value="1">1</option>
                            <?php } ?>
                            <?php if (!$valorDoisEncontrado) { ?>
                                <option value="2">2</option>
                            <?php } ?>
                            <?php if (!$valorTresEncontrado) { ?>
                                <option value="3">3</option>
                            <?php } ?>
                    </select>
                </div>
                <div class="form-group col-xs-6 mt-4 d-flex flex-row">
                    <input style="display: none;" id="imgRecomendado" type="file" name="imgRecomendado">
                    <label for="preco">Imagem</label>
                    <button id="imgAlteradoRecomendado" class="btn btn-primary ml-2"> Escolher Arquivo</button>
                    <input type="text" class="form-control ml-2" placeholder="Imagem" id="inputImgAlteradoRecomendado">
                </div>
                <div class="form-group col-xs-12  text-center mt-2">
                    <button onclick="criarProdutoRecomendado()" type="button" id="btn-login" class="btn btn-custom btn-success btn-lg">Criar</button>
                    <a class="btn btn-custom btn-primary btn-lg" href="/listagemProdutoRecomendadoAdmin">Voltar</a>
                </div>
            </div>
        </div>
    </div>
</div>
<?php } ?>
<?php if (count($this->view->getProdutosRecomendados) == 3) { ?>

<div class="m-5 text-center">
    <h1>Ja tem 3 produtos recomendados cadastrados!</h1>
</div>
<?php } ?>