<?php
$produto = $this->view->getProduto;
?>

<link href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<link rel="stylesheet" href="/css/login.css">
<script src="/js/produto.js"></script>


<section id="login">
    <div class="container mt-4">
        <div class="row">
            <div class="col-xs-12">
                <div class="form-wrap">
                    <h1 class="text-primary">Criar um produto</h1>
                    <form role="form" action="/registrarProduto" method="post" id="login-form" autocomplete="off">
                        <div class="form-group">
                            <label for="nome" class="sr-only">Nome</label>
                            <input value="<?= isset($produto['nome']) ? $produto['nome'] : '' ?>" id="nome" type="text" name="nome" class="form-control" placeholder="name">
                        </div>
                        <div class="form-group">
                            <label for="preco" class="sr-only">Preço</label>
                            <input value="<?= isset($produto['preco']) ? $produto['preco'] : '' ?>" id="preco" name="preco" class="form-control" placeholder="Preço">
                        </div>
                        <div class="form-group">
                            <label class="sr-only">Descricao</label>
                            <input value="<?= isset($produto['descricao']) ? $produto['descricao'] : '' ?>" id="descricao" type="text" name="descricao" class="form-control" placeholder="Descricao">
                        </div>
                        <div> <h4>Imagem Principal:</h4></div>
                        <div class="form-group">
                            <input multiple="multiple" type="file" name="img" id="img" class="form-control" placeholder="Imagem">
                        </div>
                        <div> <h4>Imagens Opcionais:</h4></div>
                        <div class="form-group">
                            <input multiple="multiple" type="file" name="img2" id="img2" class="form-control" placeholder="Imagem">
                        </div>
                        <div class="form-group">
                            <input multiple="multiple" type="file" name="img3" id="img3" class="form-control" placeholder="Imagem">
                        </div>
                        <div class="form-group">
                            <input multiple="multiple" type="file" name="img4" id="img4" class="form-control" placeholder="Imagem">
                        </div>
                        <button onclick="criarProduto()" type="button" id="btn-login" class="btn btn-custom btn-success btn-lg btn-block">Criar</button>
                    </form>
                    <hr>
                </div>
            </div>
        </div>
    </div> 
</section>