<?php
$produto = $this->view->getProduto;
?>

<link href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<link rel="stylesheet" href="/css/all.css">
<link rel="stylesheet" href="/css/cadastro.css">
<script src="/js/produto.js"></script>

<div style="display: none;" class="alert alert-danger m-5 text-center" id="al-produto-img" role="alert">
    Selecione uma imagem PNG ou JPG para a imagem principal
</div>
<div class="container mt-5 mb-4 produto-container">
    <div class="row">
        <div class="col-xs-12 mb-4">
            <div class="form-wrap">
                <h1 style="font-family: Stencil Std, fantasy" class="text-dark text-center">Cadastre um produto</h1>
                <br>
                <div class="form-group col-xs-6">
                    <label for="nome">Nome</label>
                    <input value="<?= isset($produto['nome']) ? $produto['nome'] : '' ?>" id="nome" type="text" name="nome" class="form-control" placeholder="name">
                    <p id="p-produto-nome">Digite o nome</p>
                </div>
                <div class="form-group col-xs-6">
                    <label for="preco">Preço:</label>
                    <input value="<?= isset($produto['preco']) ? $produto['preco'] : '' ?>" id="preco" name="preco" class="form-control" placeholder="Preço">
                    <p id="p-produto-preco">Digite o preço</p>
                </div>
                <div class="form-group col-xs-6">
                    <label>Descricao:</label>
                    <input value="<?= isset($produto['descricao']) ? $produto['descricao'] : '' ?>" id="descricao" type="text" name="descricao" class="form-control" placeholder="Descricao">
                    <p id="p-produto-descricao">Digite a descriçao</p>
                </div>
                <div class="form-group col-xs-6 d-flex flex-column">
                    <div>
                        <label>Imagem Principal:</label>
                    </div>
                    <div class="d-flex flex-row">
                        <input style="display: none;" id="img" type="file" name="img">
                        <button id="imgAlterado" class="btn btn-primary btn-sm"> Escolher Arquivo</button>
                        <input type="text" class="form-control ml-2 mt-2" placeholder="Imagem" id="inputImgAlterado">
                    </div>
                </div>
                <div class="form-group col-xs-12 text-center">
                    <h3>Imagem Opcionais:</h3>
                </div>
                <div class="form-group col-xs-4 d-flex flex-column">
                    <div>
                        <label>Imagem 2:</label>
                    </div>
                    <div class="d-flex flex-row">
                        <input style="display: none;" id="img2" type="file" name="img2">
                        <button id="imgAlterado2" class="btn btn-primary btn-sm ml-1"> Escolher Arquivo</button>
                        <input type="text" class="form-control ml-2 mt-2" placeholder="Imagem" id="inputImgAlterado2">
                    </div>
                </div>
                <div class="form-group col-xs-4 d-flex flex-column">
                    <div>
                        <label>Imagem 3:</label>
                    </div>
                    <div class="d-flex flex-row">
                    <input style="display: none;" id="img3" type="file" name="img3">
                    <button id="imgAlterado3" class="btn btn-primary btn-sm ml-1"> Escolher Arquivo</button>
                    <input type="text" class="form-control ml-2 mt-2" placeholder="Imagem" id="inputImgAlterado3">
                    </div>
                </div>
                <div class="form-group col-xs-4 d-flex flex-column">
                <div>
                        <label>Imagem 4:</label>
                    </div>
                    <div class="d-flex flex-row">
                    <input style="display: none;" id="img4" type="file" name="img4">
                    <button id="imgAlterado4" class="btn btn-primary btn-sm ml-1"> Escolher Arquivo</button>
                    <input type="text" class="form-control ml-2 mt-2" placeholder="Imagem" id="inputImgAlterado4">
                    </div>
                </div>
                <div class="form-group col-xs-12  text-center mt-3">
                    <button style="width: 150px;" onclick="criarProduto()" type="button" class="btn btn-custom btn-success btn-lg">Criar</button>
                    <a style="width: 150px;" class="btn btn-custom btn-info btn-lg" href="/listagemProdutoAdmin">Voltar</a>
                </div>
            </div>
        </div>
    </div>
</div>