<?php
$usuario = $this->view->getUsuario;
?>

<link href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<link rel="stylesheet" href="/css/login.css">
<script src="/js/login.js"></script>
<script src="/js/usuario.js"></script>

<div class="container">
    <div class="row">
        <div class="col-xs-12">
            <div class="form-wrap">
                <h1 class="text-primary text-center">Criar um usuario</h1>
                <br>
                <form role="form" action="/registrarUsuario" method="POST" id="login-form" autocomplete="off">
                    <div class="form-group col-xs-6">
                        <label for="nome" class="sr-only">Nome</label>
                        <input value="<?= isset($usuario['nome']) ? $usuario['nome'] : '' ?>" id="nome" type="text" name="nome" id="nome" class="form-control " placeholder="name">
                    </div>
                    <div class="form-group col-xs-6">
                        <label for="email" class="sr-only">Email</label>
                        <input value="<?= isset($usuario['email']) ? $usuario['email'] : '' ?>" id="email" type="text" name="email" id="email" class="form-control" placeholder="somebody@example.com">
                    </div>
                    <div class="form-group col-xs-6">
                        <label for="key" class="sr-only">Data de Nascimento</label>
                        <input value="<?= isset($usuario['data_nascimento']) ? $usuario['data_nascimento'] : '' ?>" id="nascimento" type="date" name="data_nascimento" id="key" class="form-control" placeholder="Password">
                    </div>
                    <div class="form-group col-xs-6">
                        <label for="key" class="sr-only">Telefone</label>
                        <input value="<?= isset($usuario['telefone']) ? $usuario['telefone'] : '' ?>" maxlength="11" id="tel" type="text" name="telefone" id="key" class="form-control" placeholder="Telefone">
                    </div>
                    <div class="form-group col-xs-4">
                        <label for="key" class="sr-only">Senha</label>
                        <input value="<?= isset($usuario['senha']) ? $usuario['senha'] : '' ?>" type="password" id="senha" name="senha" id="key" class="form-control" placeholder="Senha">
                    </div>
                    <div class="form-group col-xs-4">
                        <label for="key" class="sr-only">Repetir Senha</label>
                        <input type="password" name="repetirSenha" class="form-control" id="repetirSenha" placeholder="Repetir Senha">
                    </div>
                    <div class="form-group col-xs-4 ml-auto">
                        <input type="file" name="img" id="img" class="form-control" placeholder="Imagem">
                    </div>
                    <hr>
                    <div class="form-group col-xs-12 text-center">
                        <button onclick="criarUsuario()" type="button" id="btn-cadastro-usuario" class="btn btn-custom btn-info btn-lg btn-block">Criar</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>