<link href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<link rel="stylesheet" href="/css/login.css">
<script src="/js/login.js"></script>
<script src="/js/usuario.js"></script>
<!------ Include the above in your HEAD tag ---------->
<div class="container mt-4">
    <div class="row">
        <div class="col-xs-12">
            <div class="form-wrap">
                <h1 class="text-primary text-center">Editar o usuario <?= $this->view->getUsuario['nome'] ?> </h1>
                <br>
                <div class="form-group col-xs-6">
                    <label for="nome" class="sr-only">Nome</label>
                    <input value="<?= $this->view->getUsuario['id'] ?>" id="id" type="hidden" name="id">
                    <input value="<?= $this->view->getUsuario['nome'] ?>" id="nome" type="text" name="nome" id="nome" class="form-control " placeholder="name">
                </div>
                <div class="form-group col-xs-6">
                    <label for="email" class="sr-only">Email</label>
                    <input value="<?= $this->view->getUsuario['email'] ?>" id="email" type="text" name="email" id="email" class="form-control" placeholder="somebody@example.com">
                </div>
                <div class="form-group col-xs-6">
                    <label for="key" class="sr-only">Data de Nascimento</label>
                    <input value="<?= $this->view->getUsuario['data_nascimento'] ?>" id="nascimento" type="date" name="data_nascimento" id="key" class="form-control" placeholder="Password">
                </div>
                <div class="form-group col-xs-6">
                    <label for="key" class="sr-only">Telefone</label>
                    <input value="<?= $this->view->getUsuario['telefone'] ?>" maxlength="11" id="tel" type="text" name="telefone" id="key" class="form-control" placeholder="Telefone">
                </div>
                <div class="form-group col-xs-4">
                    <label for="key" class="sr-only">Senha</label>
                    <input value="<?= isset($usuario['senha']) ? $usuario['senha'] : '' ?>" type="password" id="senha" name="senha" id="key" class="form-control" placeholder="Senha">
                </div>
                <div class="form-group col-xs-4">
                    <label for="key" class="sr-only">Repetir Senha</label>
                    <input type="password" name="repetirSenha" class="form-control" id="repetirSenha" placeholder="Repetir Senha">
                </div>
                <div class="form-group col-xs-4 d-flex flex-row">
                    <input style="display: none;" id="img" type="file" name="img">
                    <button id="imgAlterado" class="btn btn-primary"> Escolher Arquivo</button>
                    <input type="text" class="form-control ml-2" placeholder="Imagem" id="inputImgAlterado">
                </div>
                <hr>
                <div class="form-group col-xs-12 text-center">
                    <button onclick="editarUsuario()" type="button" id="btn-editar-usuario" class="btn btn-custom btn-info btn-lg btn-block">Editar</button>
                </div>
            </div>
        </div> <!-- /.col-xs-12 -->
    </div> <!-- /.row -->
</div> <!-- /.container -->