<link href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<link rel="stylesheet" href="/css/login.css">
<script src="/js/login.js"></script>
<script src="/js/usuario.js"></script>
<!------ Include the above in your HEAD tag ---------->

<section id="login">
    <div class="container mt-4">
        <div class="row">
            <div class="col-xs-12">
                <div class="form-wrap">
                    <h1 class="text-primary">Editar o usuario <?= $this->view->getUsuario['nome'] ?> </h1>
                    <form role="form" action="/editarUsuario" method="post" id="login-form" autocomplete="off">
                        <input type="hidden" id="id" name="id" value="<?= $this->view->getUsuario['id'] ?>">
                        <div class="form-group">
                            <label for="nome" class="sr-only">Nome</label>
                            <input type="text" value="<?= $this->view->getUsuario['nome'] ?>" id="nome" name="nome" id="nome" class="form-control" placeholder="name">
                        </div>
                        <div class="form-group">
                            <label for="email" class="sr-only">Email</label>
                            <input value="<?= $this->view->getUsuario['email'] ?>" type="text" id="email" name="email" id="email" class="form-control" placeholder="somebody@example.com">
                        </div>
                        <div class="form-group">
                            <label for="key" class="sr-only">Data de Nascimento</label>
                            <input value="<?= $this->view->getUsuario['data_nascimento'] ?>" id="nascimento" type="date" name="data_nascimento"  class="form-control">
                        </div>
                        <div class="form-group">
                            <label class="sr-only">Telefone</label>
                            <input value="<?= $this->view->getUsuario['telefone'] ?>" maxlength="11" id="tel"  type="text" name="telefone" class="form-control" placeholder="Telefone">
                        </div>
                        <div class="form-group">
                            <label for="key" class="sr-only">Password</label>
                            <input type="password" name="senha" class="form-control" id="senha"  placeholder="Senha">
                        </div>
                        <div class="form-group">
                            <label for="key" class="sr-only">Repetir Senha</label>
                            <input type="password" name="repetirSenha" id="repetirSenha" class="form-control" placeholder="Repetir Senha">
                        </div>
                        <div class="form-group">
                        <input type="file" name="img" id="img" class="form-control" placeholder="Imagem">
                        </div>
                        <div class="checkbox">
                            <span class="character-checkbox" onclick="showPassword()"></span>
                            <span class="label">Show password</span>
                        </div>
                        <button onclick="editarUsuario()" type="button" id="btn-editar-usuario" class="btn btn-custom btn-success btn-lg btn-block">Criar</button>
                    </form>
                    <hr>
                </div>
            </div> <!-- /.col-xs-12 -->
        </div> <!-- /.row -->
    </div> <!-- /.container -->
</section>