<?php
$erroImportacao =  $this->view->getErrosImportacao;
?>

<script>
  $(document).ready(function() {
    getDataTable('#listagem-produtos');

    $('.btn-importacao-produto').click(function() {
      $('#modal-importacao-produto').modal('show');
    })
  })

  function importarProduto() {
    let formData = new FormData();
    let arquivo = $('#inputImportacaoProduto')[0].files[0];
    formData.append('arquivoProdutoImportacao', arquivo);
    $.ajax({
      url: '/importarProduto',
      type: 'POST',
      data: formData,
      processData: false,
      contentType: false,
      success: function(response) {
        window.location.href = "/listagemProdutoAdmin"
      },
    })
  }

  function remover(id, nome) {
    $.ajax({
      url: 'deletarProduto',
      type: 'POST',
      data: {
        idProduto: id,
        nome: nome
      },
      success: function(response) {
        $('#exampleModal').modal('toggle');
        if (response.sucesso) {
          var divSucesso = document.getElementById("remover-produto-sucesso");
          divSucesso.className = 'alert alert-success m-5 text-center'
          let p = document.createElement('p');
          p.innerText = "Produto removido com sucesso";
          divSucesso.appendChild(p);
          setTimeout(() => {
            window.location.href = "/listagemProdutoAdmin"
          }, 1000)
        }
      }
    })
  }

  function getDataTable(id) {
    $(id).DataTable({
      "ordering": true,
      "paging": true,
      "searching": true,
      "oLanguage": {
        "sEmptyTable": "Nenhum registro encontrado na tabela",
        "sInfo": "Mostrar _START_ até _END_ de _TOTAL_ registros",
        "sInfoEmpty": "Mostrar 0 até 0 de 0 Registros",
        "sInfoFiltered": "(Filtrar de _MAX_ total registros)",
        "sInfoPostFix": "",
        "sInfoThousands": ".",
        "sLengthMenu": "Mostrar _MENU_ registros por pagina",
        "sLoadingRecords": "Carregando...",
        "sProcessing": "Processando...",
        "sZeroRecords": "Nenhum registro encontrado",
        "sSearch": "Pesquisar",
        "oPaginate": {
          "sNext": "Proximo",
          "sPrevious": "Anterior",
          "sFirst": "Primeiro",
          "sLast": "Ultimo"
        },
        "oAria": {
          "sSortAscending": ": Ordenar colunas de forma ascendente",
          "sSortDescending": ": Ordenar colunas de forma descendente"
        }
      }
    });
    $('.modal-button').click(function(e) {
      let text = e.target.id;
      let idText = text.split("-");
      let nome = idText[3];
      let id = idText[4];

      $('.button-remover').attr("onclick", `remover(${id},"${nome}")`)
      $('.modal-body').html("Deseja remover o produto " + nome + "?");
      $('#exampleModal').modal('show');
    })
  }
</script>
<link rel="stylesheet" href="/css/all.css">
<br>
<div id="remover-produto-sucesso" class="mt-5"></div>
<h1 class="text-center mt-2">Produtos</h1>

<a style="height:40px;padding:8px" href="/cadastroProdutoAdmin" class="btn btn-primary btn-produto-cadastrar btn-sm  ml-5 mt-5">Cadastrar</a>
<br>
<div class="d-flex justify-content-end">
  <button class="btn btn-info mr-2 btn-importacao-produto" type="button" aria-haspopup="true" aria-expanded="false">
    Importar
  </button>
  <div class="dropdown d-flex justify-content-end mr-5">
    <button class="btn btn-info dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      Exportar
    </button>
    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
      <form method="post" action="/exportarCsvProduto" class="text-center">
        <button type="submit" class="btn btn-light btn-block">CSV</button>
      </form>
      <hr class="border border-dark">
      <form method="post" action="/exportarXlsProduto" class="text-center">
        <button type="submit" class="btn btn-light btn-block">XLS</button>
      </form>
    </div>
  </div>
</div>
<table class="table mb-5" id="listagem-produtos">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Id</th>
      <th scope="col">Nome</th>
      <th scope="col">Preço</th>
      <th scope="col">Data de Criação</th>
      <th scope="col">Data de Alteração</th>
      <th scope="col">Ações</th>
    </tr>
  </thead>
  <tbody>
    <?php foreach ($this->view->getProdutos as $produto) { ?>
      <tr>
        <td scope="row"><?= $produto['id'] ?></td>
        <td><?= $produto['nome'] ?></td>
        <td><?= (number_format($produto['preco'], 2, ',', '')) ?></td>
        </td>
        <td><?= date('d/m/Y H:i:s', strtotime($produto['data_criacao'])) ?></td>
        <td><?= date('d/m/Y H:i:s', strtotime($produto['data_alteracao'])) ?></td>
        <td>
          <a href="/editarProdutoAdmin/<?= $produto['id'] ?>" style="color: white;" class="btn btn-info btn-sm">Editar</a>
          <button id="id-button-modal-<?= $produto['nome'] ?>-<?= $produto['id'] ?>" style="color: white;" class="btn btn-danger btn-sm modal-button">Remover</button>
        </td>
      <?php }
      ?>
      </tr>
  </tbody>
</table>


<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body" id="">
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-info" data-dismiss="modal">Fechar</button>
        <button onclick type="button" class="btn btn-danger button-remover">Remover</button>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="modal-importacao-produto" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body" id="">
        <h4 class="text-center" style="text-transform: capitalize;font-family: Stencil Std, fantasy">Importe</h4>
        <div>
          <p capitalize>Baixe o <a href="/template_importacao.csv" download="template_importacao.csv">template</a></p>
        </div>
        <input type="file" class="form-control ml-2" placeholder="Imagem" id="inputImportacaoProduto">
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal">Fechar</button>
        <button onclick="importarProduto()" type="button" class="btn btn-success">Importar</button>
      </div>
    </div>
  </div>
</div>