

<table class="table mb-5" id="listagem-pedido-produto">
  <thead class="thead-dark">
    <th scope="col">Nome</th>
    <th scope="col">Quantidade</th>
    <th scope="col">Preço</th>
    </tr>
  </thead>
  <tbody>
    <?php foreach ($this->view->getPedidoProduto as $produto) { ?>
      <tr>
        <td><?= $produto['nome']  ?></td>
        </td>
        <td><?= $produto['quantidade_produto']  ?></td>
        <td><?= (number_format($produto['preco_total'], 2, ',', '')) ?></td>
      <?php }
      ?>
      </tr>
  </tbody>
</table>