<script>
  $(document).ready(function() {
    getDataTable('#listagem-produtos-recomendados');
  })

  function removerProdutoRecomendado(id, nome) {
    $.ajax({
      url: 'deletarProdutoRecomendado',
      type: 'POST',
      data: {
        idProdutoRecomendado: id,
        nomeProdutoRecomendado: nome
      },
      success: function(response) {
        window.location.href = "/listagemProdutoRecomendadoAdmin"
        alert("Deletado com sucesso")
      },
      error: function(e) {
        window.location.href = "/listagemProdutoRecomendadoAdmin"
        alert("Ocorreu um erro")
      }
    })
  }

  function getDataTable(id) {
    $(id).DataTable({
      "ordering": true,
      "paging": true,
      "searching": true,
      "oLanguage": {
        "sEmptyTable": "Nenhum registro encontrado na tabela",
        "sInfo": "Mostrar _START_ até _END_ de _TOTAL_ registros",
        "sInfoEmpty": "Mostrar 0 até 0 de 0 Registros",
        "sInfoFiltered": "(Filtrar de _MAX_ total registros)",
        "sInfoPostFix": "",
        "sInfoThousands": ".",
        "sLengthMenu": "Mostrar _MENU_ registros por pagina",
        "sLoadingRecords": "Carregando...",
        "sProcessing": "Processando...",
        "sZeroRecords": "Nenhum registro encontrado",
        "sSearch": "Pesquisar",
        "oPaginate": {
          "sNext": "Proximo",
          "sPrevious": "Anterior",
          "sFirst": "Primeiro",
          "sLast": "Ultimo"
        },
        "oAria": {
          "sSortAscending": ": Ordenar colunas de forma ascendente",
          "sSortDescending": ": Ordenar colunas de forma descendente"
        }
      }
    });
    $('.modal-button').click(function(e) {
      let text = e.target.id;
      let idText = text.split("-");
      let nome = idText[3];
      let id = idText[4];

      $('.button-remover').attr("onclick", `removerProdutoRecomendado(${id},"${nome}")`)
      $('.modal-body').html("Deseja remover o produto " + nome + "?");
      $('#exampleModal5').modal('show');
    })
  }
</script>
<link rel="stylesheet" href="/css/all.css">

<a style="height:40px;padding:8px" href="/cadastroProdutoRecomendadoAdmin" class="btn btn-primary btn-produto-recomendado-cadastrar btn-sm  ml-5 mt-5">Cadastrar</a>
<div class="dropdown d-flex justify-content-end mr-5">
  <button class="btn btn-info dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Exportar
  </button>
  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
    <form method="post" action="/exportarCsvProdutoRecomendado" class="text-center">
      <button type="submit" class="btn btn-info btn-block">CSV</button>
    </form>
    <form method="post" action="/exportarXlsProdutoRecomendado" class="text-center">
      <button type="submit" class="btn btn-info btn-block">XLS</button>
    </form>
  </div>
</div>
<table class="table mb-5" id="listagem-produtos-recomendados">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Nome Imagem</th>
      <th scope="col">Caminho Arquivo</th>
      <th scope="col">Numero de Sequencia</th>
      <th scope="col">Data de Criação</th>
      <th scope="col">Data de Alteração</th>
      <th scope="col">Ações</th>
    </tr>
  </thead>
  <tbody>
    <?php foreach ($this->view->getProdutosRecomendados as $produto) { ?>
      <tr>
        <td scope="row"><?= $produto['nome_imagem'] ?></td>
        <td><?= $produto['arquivo']  ?></td>
        <td><?= $produto['numero_sequencia']  ?></td>
        <td><?= date('d/m/Y H:i:s', strtotime($produto['data_criacao'])) ?></td>
        <td><?= date('d/m/Y H:i:s', strtotime($produto['data_alteracao'])) ?></td>
        <td>
          <a href="/editarProdutoRecomendadoAdmin/<?= $produto['id'] ?>" style="color: white;" class="btn btn-info btn-sm">Editar</a>
          <button id="id-button-modal-<?= $produto['nome_imagem'] ?>-<?= $produto['id'] ?>" style="color: white;" class="btn btn-danger btn-sm modal-button">Remover</button>
        </td>
      <?php }
      ?>
      </tr>
  </tbody>
</table>


<div class="modal fade" id="exampleModal5" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body" id="">
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-info" data-dismiss="modal">Fechar</button>
        <button onclick type="button" class="btn btn-danger button-remover">Remover</button>
      </div>
    </div>
  </div>
</div>