

<table class="table mb-5" id="listagem-pedido-produto">
  <thead class="thead-dark">
    <th scope="col">Nome</th>
    <th scope="col">Quantidade</th>
    </tr>
  </thead>
  <tbody>
    <?php foreach ($this->view->getPedidoProduto as $produto) { ?>
      <tr>
        <td style="font-family: Impact, fantasy;font-weight:400;font-size:13pt"><?= $produto['nome']  ?></td>
        </td>
        <td><?= $produto['quantidade_produto']  ?></td>
      <?php }
      ?>
      </tr>
  </tbody>
</table>

<div class="text-center"  style="font-family: Impact, fantasy;font-weight:400;font-size:17pt">
  Preço Total : <?=$this->view->getPedidoProduto[0]['preco_total']  ?>
</div>