<script>
  $(document).ready(function() {
    getDataTable('#listagem-usuarios');
  })

  function remover(id) {
    $.ajax({
      url: 'deletarUsuario',
      type: 'POST',
      data: {
        idUsuario: id
      },
      success: function(response) {
        window.location.href = "/listagemUsuarioAdmin"
        alert("Deletado com sucesso")
      },
      error: function(e) {
        window.location.href = "/listagemUsuarioAdmin"
        alert("Ocorreu um erro")
      }
    })
  }

  function getDataTable(id) {
    $(id).DataTable({
      "ordering": true,
      "paging": true,
      "searching": true,
      "oLanguage": {
        "sEmptyTable": "Nenhum registro encontrado na tabela",
        "sInfo": "Mostrar _START_ até _END_ de _TOTAL_ registros",
        "sInfoEmpty": "Mostrar 0 até 0 de 0 Registros",
        "sInfoFiltered": "(Filtrar de _MAX_ total registros)",
        "sInfoPostFix": "",
        "sInfoThousands": ".",
        "sLengthMenu": "Mostrar _MENU_ registros por pagina",
        "sLoadingRecords": "Carregando...",
        "sProcessing": "Processando...",
        "sZeroRecords": "Nenhum registro encontrado",
        "sSearch": "Pesquisar",
        "oPaginate": {
          "sNext": "Proximo",
          "sPrevious": "Anterior",
          "sFirst": "Primeiro",
          "sLast": "Ultimo"
        },
        "oAria": {
          "sSortAscending": ": Ordenar colunas de forma ascendente",
          "sSortDescending": ": Ordenar colunas de forma descendente"
        }
      }
    });
    $('.modal-button').click(function(e) {
      let text = e.target.id;
      let idText = text.split("-");
      let nome = idText[3];
      let id = idText[4];

      $('.button-remover').attr("onclick", `remover(${id})`)
      $('.modal-body').html("Deseja remover o usuario " + nome);
      $('#exampleModal').modal('show');
    })
  }
</script>

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="/css/login.css">
</head>

<body>
  <table class="table mt-4" id="listagem-usuarios">
    <thead class="thead-dark">
      <tr>
        <th scope="col">Email</th>
        <th scope="col">Nome</th>
        <th scope="col">Data de Criação</th>
        <th scope="col">Data de Alteração</th>
        <th scope="col">Ações</th>
      </tr>
    </thead>
    <tbody>
      <?php foreach ($this->view->getUsuarios as $usuario) { ?>
        <tr>
          <td scope="row"><?= $usuario['email'] ?></td>
          <td><?= $usuario['nome'] ?></td>
          </td>
          <td><?= date('d/m/Y H:i:s', strtotime($usuario['data_criacao'])) ?></td>
          <td><?= date('d/m/Y H:i:s', strtotime($usuario['data_alteracao'])) ?></td>
          <td>
            <a href="/editarUsuarioAdmin/<?= $usuario['id'] ?>" style="color: white;" class="btn btn-info btn-sm">Editar</a>
            <button id="id-button-modal-<?= $usuario['nome'] ?>-<?= $usuario['id'] ?>" style="color: white;" class="btn btn-danger btn-sm modal-button">Remover</button>
          </td>
        <?php }
        ?>
        </tr>
    </tbody>
  </table>

  <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body" id="">
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-info" data-dismiss="modal">Fechar</button>
          <button onclick type="button" class="btn btn-danger button-remover">Remover</button>
        </div>
      </div>
    </div>
  </div>
</body>

</html>