<html>

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="/css/login.css">

  <script>
    $(document).ready(function() {
      getDataTable('#listagem-pedidos');
      getDataTable('#listagem-pedido-produto');
    })
    function abrirPedido(pedidoId) {
      $('#modal-body-produtos').load(
        "/listagemPedidoProdutoAdmin", 
        {
          pedidoId: pedidoId
        });
        $('#modal-produtos').modal('show');
    }
    function getDataTable(id) {
      $(id).DataTable({
        "ordering": true,
        "paging": true,
        "searching": true,
        "oLanguage": {
          "sEmptyTable": "Nenhum registro encontrado na tabela",
          "sInfo": "Mostrar _START_ até _END_ de _TOTAL_ registros",
          "sInfoEmpty": "Mostrar 0 até 0 de 0 Registros",
          "sInfoFiltered": "(Filtrar de _MAX_ total registros)",
          "sInfoPostFix": "",
          "sInfoThousands": ".",
          "sLengthMenu": "Mostrar _MENU_ registros por pagina",
          "sLoadingRecords": "Carregando...",
          "sProcessing": "Processando...",
          "sZeroRecords": "Nenhum registro encontrado",
          "sSearch": "Pesquisar",
          "oPaginate": {
            "sNext": "Proximo",
            "sPrevious": "Anterior",
            "sFirst": "Primeiro",
            "sLast": "Ultimo"
          },
          "oAria": {
            "sSortAscending": ": Ordenar colunas de forma ascendente",
            "sSortDescending": ": Ordenar colunas de forma descendente"
          }
        }
      });
    }
  </script>
</head>

<body>
  <div class="dropdown d-flex justify-content-end mr-5">
    <button class="btn btn-info dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      Exportar
    </button>
    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
      <form method="post" action="/exportarCsvPedido" class="text-center">
        <button type="submit" class="btn btn-info btn-block">CSV</button>
      </form>
      <form method="post" action="/exportarXlsPedido" class="text-center">
        <button type="submit" class="btn btn-info btn-block">XLS</button>
      </form>
    </div>
  </div>
  <table class="table mb-5" id="listagem-pedidos">
    <thead class="thead-dark">
      <tr>
        <th scope="col">Id</th>
        <th scope="col">Quantidade de Produtos</th>
        <th scope="col">Usuario Comprador</th>
        <th scope="col">Preço Total</th>
        <th scope="col">Ações</th>
      </tr>
    </thead>
    <tbody>
      <?php foreach ($this->view->getPedidos as $pedido) { ?>
        <tr>
          <td scope="row"><?= $pedido['id'] ?></td>
          <td><?= $pedido['quantidade_produtos']  ?></td>
          </td>
          <td><?= $pedido['email']  ?></td>
          <td><?= (number_format($pedido['preco_total'], 2, ',', '')) ?></td>
          <td>
            <button onclick="abrirPedido(<?= $pedido['id'] ?>)" 
                style="color: white;" class="btn btn-info btn-sm">Produtos</button>
          </td>
        <?php }
        ?>
        </tr>
    </tbody>
  </table>


  <div class="modal fade" id="modal-produtos" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div id="modal-body-produtos"></div>
        <div class="modal-footer">
          <button type="button" class="btn btn-danger" data-dismiss="modal">Fechar</button>
        </div>
      </div>
    </div>
  </div>
</body>

</html>