<script>
  $(document).ready(function() {
    getDataTable('#listagem-usuarios');

    $('.btn-importacao-usuario').click(function() {
      $('#modal-importacao-usuario').modal('show');
    })
  })

  function remover(id) {
    $.ajax({
      url: 'deletarUsuario',
      type: 'POST',
      data: {
        idUsuario: id
      },
      success: function(response) {
        $('#exampleModal').modal('toggle');
        if (response.sucesso) {
          var divSucesso = document.getElementById("remover-usuario-sucesso");
          divSucesso.className = 'alert alert-success m-5 text-center'
          let p = document.createElement('p');
          p.innerText = "Usuario removido com sucesso";
          divSucesso.appendChild(p);
          setTimeout(() => {
            window.location.href = "/listagemUsuarioAdmin"
          }, 1000)
        }
      }
    })
  }

  function importarUsuario() {
    let formData = new FormData();
    let arquivo = $('#inputInportacaoUsuario')[0].files[0];
    formData.append('arquivoUsuarioImportacao', arquivo);
    $.ajax({
      url: '/importarUsuario',
      type: 'POST',
      data: formData,
      processData: false,
      contentType: false,
      success: function(response) {
        window.location.href = "/listagemUsuarioAdmin"
      },
    })
  }

  function getDataTable(id) {
    $(id).DataTable({
      "ordering": true,
      "paging": true,
      "searching": true,
      "oLanguage": {
        "sEmptyTable": "Nenhum registro encontrado na tabela",
        "sInfo": "Mostrar _START_ até _END_ de _TOTAL_ registros",
        "sInfoEmpty": "Mostrar 0 até 0 de 0 Registros",
        "sInfoFiltered": "(Filtrar de _MAX_ total registros)",
        "sInfoPostFix": "",
        "sInfoThousands": ".",
        "sLengthMenu": "Mostrar _MENU_ registros por pagina",
        "sLoadingRecords": "Carregando...",
        "sProcessing": "Processando...",
        "sZeroRecords": "Nenhum registro encontrado",
        "sSearch": "Pesquisar",
        "oPaginate": {
          "sNext": "Proximo",
          "sPrevious": "Anterior",
          "sFirst": "Primeiro",
          "sLast": "Ultimo"
        },
        "oAria": {
          "sSortAscending": ": Ordenar colunas de forma ascendente",
          "sSortDescending": ": Ordenar colunas de forma descendente"
        }
      }
    });
    $('.modal-button').click(function(e) {
      let text = e.target.id;
      let idText = text.split("-");
      let nome = idText[3];
      let id = idText[4];

      $('.button-remover').attr("onclick", `remover(${id})`)
      $('.modal-body').html("Deseja remover o usuario " + nome);
      $('#exampleModal').modal('show');
    })
  }
</script>
<link rel="stylesheet" href="/css/all.css">

<br>
<div id="remover-usuario-sucesso" class="mt-5"></div>

<h1 class="text-center mt-2">Usuarios</h1>
<a style="height:40px;padding:8px" href="/cadastroUsuarioAdmin" class="btn btn-primary btn-usuario-cadastrar btn-sm  ml-5 mt-5">Cadastrar</a>
<div class="d-flex justify-content-end">
  <button class="btn btn-info mr-2 btn-importacao-usuario" type="button" aria-haspopup="true" aria-expanded="false">
    Importar
  </button>
  <div class="dropdown d-flex justify-content-end mr-5">
    <button class="btn btn-info dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      Exportar
    </button>
    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
      <form method="post" action="/exportarCsvUsuario" class="text-center">
        <button type="submit" class="btn btn-light btn-block">CSV</button>
      </form>
      <hr class="border border-dark">
      <form method="post" action="/exportarXlsUsuario" class="text-center">
        <button type="submit" class="btn btn-light btn-block">XLS</button>
      </form>
    </div>
  </div>
</div>
<table class="table mt-3" id="listagem-usuarios">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Email</th>
      <th scope="col">Nome</th>
      <th scope="col">Data de Criação</th>
      <th scope="col">Data de Alteração</th>
      <th scope="col">Ações</th>
    </tr>
  </thead>
  <tbody>
    <?php foreach ($this->view->getUsuarios as $usuario) { ?>
      <tr>
        <td scope="row"><?= $usuario['email'] ?></td>
        <td><?= $usuario['nome'] ?></td>
        </td>
        <td><?= date('d/m/Y H:i:s', strtotime($usuario['data_criacao'])) ?></td>
        <td><?= date('d/m/Y H:i:s', strtotime($usuario['data_alteracao'])) ?></td>
        <td>
          <a href="/editarUsuarioAdmin/<?= $usuario['id'] ?>" style="color: white;" class="btn btn-info btn-sm">Editar</a>
          <button id="id-button-modal-<?= $usuario['nome'] ?>-<?= $usuario['id'] ?>" style="color: white;" class="btn btn-danger btn-sm modal-button">Remover</button>
        </td>
      <?php }
      ?>
      </tr>
  </tbody>
</table>

<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body" id="">
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-info" data-dismiss="modal">Fechar</button>
        <button onclick type="button" class="btn btn-danger button-remover">Remover</button>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="modal-importacao-usuario" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body text-center" id="">
        <h4 style="text-transform: capitalize;font-family: Stencil Std, fantasy">Importe</h4>
        <div class="text-left">
          <p>Baixe o <a href="/template_importacao_usuario.csv" download="template_importacao_usuario.csv">template</a></p>
        </div>
        <input type="file" class="form-control ml-2" placeholder="Imagem" id="inputInportacaoUsuario">
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal">Fechar</button>
        <button onclick="importarUsuario()" type="button" class="btn btn-success button-inportar">Importar</button>
      </div>
    </div>
  </div>
</div>