<script>
  $(document).ready(function() {
    getDataTable('#listagem-favoritos');
  })

  function getDataTable(id) {
    $(id).DataTable({
      "ordering": true,
      "paging": true,
      "searching": true,
      "oLanguage": {
        "sEmptyTable": "Nenhum registro encontrado na tabela",
        "sInfo": "Mostrar _START_ até _END_ de _TOTAL_ registros",
        "sInfoEmpty": "Mostrar 0 até 0 de 0 Registros",
        "sInfoFiltered": "(Filtrar de _MAX_ total registros)",
        "sInfoPostFix": "",
        "sInfoThousands": ".",
        "sLengthMenu": "Mostrar _MENU_ registros por pagina",
        "sLoadingRecords": "Carregando...",
        "sProcessing": "Processando...",
        "sZeroRecords": "Nenhum registro encontrado",
        "sSearch": "Pesquisar",
        "oPaginate": {
          "sNext": "Proximo",
          "sPrevious": "Anterior",
          "sFirst": "Primeiro",
          "sLast": "Ultimo"
        },
        "oAria": {
          "sSortAscending": ": Ordenar colunas de forma ascendente",
          "sSortDescending": ": Ordenar colunas de forma descendente"
        }
      }
    });
  }
</script>
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="/css/all.css">
</head>

<body>
  
  <div class="container">
    <h2 style="font-family: Stencil Std, fantasy;" class="text-center mt-5">Mais Favoritados</h2>
    <div class="row">
      <div class="col d-flex justify-content-center">
        <br>
        <?php foreach ($this->view->getMaisFavoritos as $maisFavoritos) { ?>
          <div class="col-sm-4 col-lg-4 col-md-4 p-5">
            <div class="caption text-center">
              <h2 style="font-family: Stencil Std, fantasy;"><?= $maisFavoritos['enumeracao'] ?> Lugar</h2>
            </div>
            <div class="caption text-center">
              <a href="/produto/<?= $maisFavoritos['produto_id'] ?>">
                <img style="height: 40%;" class="img-fluid" src="/img/<?= $maisFavoritos['produto_img_nome'] ?>">
              </a>
            </div>
            <div class="caption text-center">
              <h4 style="text-transform: capitalize" class="item-name  responsive-font-example">
                <?= $maisFavoritos['nome'] ?>
              </h4>
            </div>
          </div>
        <?php } ?>
      </div>
    </div>
  </div>
  <br>
  <div class="dropdown d-flex justify-content-end mr-5">
    <button class="btn btn-info dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      Exportar
    </button>
    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
      <form method="post" action="/exportarCsvFavorito" class="text-center">
        <button type="submit" class="btn btn-info btn-block">CSV</button>
      </form>
      <form method="post" action="/exportarXlsFavorito" class="text-center">
        <button type="submit" class="btn btn-info btn-block">XLS</button>
      </form>
    </div>
  </div>
  <table class="table mb-5" id="listagem-favoritos">
    <thead class="thead-dark">
      <tr>
        <th scope="col">Id</th>
        <th scope="col">Produto</th>
        <th scope="col">Usuario</th>
      </tr>
    </thead>
    <tbody>
      <?php foreach ($this->view->getFavoritos as $favorito) { ?>
        <tr>
          <td scope="row"><?= $favorito['id'] ?></td>
          <td><?= $favorito['nome']  ?></td>
          </td>
          <td><?= $favorito['usuario_nome']  ?></td>
        <?php }
        ?>
        </tr>
    </tbody>
  </table>