<html>

<head>
	<meta charset="utf-8" />
	<title>Miniframework</title>

	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">

	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

	<link rel="stylesheet" type="text/css" href="/css/style.css">

</head>

<body>
	<header>
		<nav class="navbar navbar-expand-lg bg-light">
			<div class="container-fluid">
				<a class="navbar-brand" href="/home">Home</a>
				<div class="collapse navbar-collapse" id="navbarNavAltMarkup">
					<div class="navbar-nav">
						<a class="nav-link" href="#">Carrinho</a>
						<a class="nav-link" href="#">Cadastrar Produtos</a>
						<a class="nav-link disabled">Disabled</a>
					</div>
				</div>
			</div>
		</nav>
	</header>
	<?= $this->content() ?>
	<br>
	<br>
	<footer>
		<div class="container">
			<div class="row">
				<div class="col-md-4 footer-column">
					<ul class="nav flex-column">
						<li class="nav-item">
							<span class="footer-title">Product</span>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="#">Product 1</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="#">Product 2</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="#">Plans & Prices</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="#">Frequently asked questions</a>
						</li>
					</ul>
				</div>
				<div class="col-md-4 footer-column">
					<ul class="nav flex-column">
						<li class="nav-item">
							<span class="footer-title">Company</span>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="#">About us</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="#">Job postings</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="#">News and articles</a>
						</li>
					</ul>
				</div>
				<div class="col-md-4 footer-column">
					<ul class="nav flex-column">
						<li class="nav-item">
							<span class="footer-title">Contact & Support</span>
						</li>
						<li class="nav-item">
							<span class="nav-link"><i class="fas fa-phone"></i>+47 45 80 80 80</span>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="#"><i class="fas fa-comments"></i>Live chat</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="#"><i class="fas fa-envelope"></i>Contact us</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="#"><i class="fas fa-star"></i>Give feedback</a>
						</li>
					</ul>
				</div>
			</div>

			<div class="text-center"><i class="fas fa-ellipsis-h"></i></div>

			<div class="row text-center">
				<div class="col-md-4 box">
					<span class="copyright quick-links">Copyright &copy; Your Website <script>
							document.write(new Date().getFullYear())
						</script>
					</span>
				</div>
				<div class="col-md-4 box">
					<ul class="list-inline social-buttons">
						<li class="list-inline-item">
							<a href="#">
								<i class="fab fa-twitter"></i>
							</a>
						</li>
						<li class="list-inline-item">
							<a href="#">
								<i class="fab fa-facebook-f"></i>
							</a>
						</li>
						<li class="list-inline-item">
							<a href="#">
								<i class="fab fa-linkedin-in"></i>
							</a>
						</li>
					</ul>
				</div>
				<div class="col-md-4 box">
					<ul class="list-inline quick-links">
						<li class="list-inline-item">
							<a href="#">Privacy Policy</a>
						</li>
						<li class="list-inline-item">
							<a href="#">Terms of Use</a>
						</li>
					</ul>
				</div>
			</div>
		</div>
	</footer>
</body>

</html>