<?php
$usuario = $this->view->getUsuario;
?>

<html>

<head>
	<meta charset="utf-8" />
	<title>Miniframework</title>

	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">

	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>


</head>

<body>
	<header class="fixed-top">
		<nav class="navbar navbar-expand-lg bg-light">
			<div class="container-fluid">
				<a class="navbar-brand" href="/homeAdmin">
					<i class="fa fa-shopping-cart" aria-hidden="true"></i>
				</a>
				<div class="collapse navbar-collapse" id="navbarNavAltMarkup">
					<div class="navbar-nav mr-5">
						<form class="mt-2" action="">
							<span>Pesquise:</span>
							<input class="ml-1" type="text" name="" id="">
						</form>
					</div>
					<div class="navbar-nav mt-2">
						<div class="dropdown show">
							<a class="btn btn-light text-primary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
								Produtos
							</a>
							<div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
								<a class="dropdown-item" href="/cadastroProdutoAdmin">Cadastrar Produto</a>
							</div>
						</div>
					</div>
					<div class="navbar-nav mt-2 ml-1">
						<div class="dropdown show">
							<a class="btn btn-light text-primary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
								Usuarios
							</a>
							<div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
								<a class="dropdown-item" href="/cadastroUsuarioAdmin">Cadastrar Usuario</a>
								<a class="dropdown-item" href="/listagemUsuarioAdmin">Lista de Usuarios</a>
								</div>
						</div>
					</div>
					<div class="navbar-nav mt-2">
						<button type="button" class="btn btn-light text-primary">
							<i class="fa fa-shopping-cart" aria-hidden="true"></i>
							Carrinho
							<span class="badge badge-light">4</span>
						</button>
						<div class="dropdown show">
							<a class="btn btn-light text-primary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
								<? if ($usuario['id'] != '') { ?>
									<?= $usuario['nome'] ?>
								<? }
								?>
							</a>
							<div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
								<? if ($usuario['id'] = '') { ?>
									<a class="dropdown-item" href="/login">Entrar</a>
								<? }
								?>
								<a class="dropdown-item" href="/sair">Sair</a>
							</div>
						</div>
					</div>
				</div>
			</div>
		</nav>
	</header>
	<br>
	<br>
	<br>

	<?= $this->content() ?>
	<footer class="fixed-bottom mb-4">
		<hr style="background-color: black;">
		<div class="container">
			<div class="row text-center">
				<div class="col-md-4 box">
					<span class="copyright quick-links">Copyright &copy; Your Website <script>
							document.write(new Date().getFullYear())
						</script>
					</span>
				</div>
				<div class="col-md-4 box">
					<i class="fa fa-shopping-cart fa-3x" aria-hidden="true"></i>
				</div>
				<div class="col-md-4 box">
					<ul class="list-inline quick-links">
						<li class="list-inline-item">
							<span href="#">Endereço:</span>
							<span href="#">Rua Rio Grande do Sul N 385</span>
						</li>
					</ul>
				</div>
			</div>
		</div>
	</footer>
</body>

</html>