<?php
$usuario = $this->view->getUsuario;
?>

<html>

<head>
	<meta charset="utf-8" />
	<title>Miniframework</title>
	<script src="cdn.datatables.net/1.13.4/js/jquery.dataTables.min.js"></script>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">

	<script src="https://code.jquery.com/jquery-3.3.1.min.js"  crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>


</head>

<body>
	<header class="fixed-top">
		<nav class="navbar navbar-expand-lg bg-light">
			<div class="container-fluid">
				<a class="navbar-brand" href="/homeAdmin">
					<i class="fa fa-shopping-cart" aria-hidden="true"></i>
				</a>
				<div class="collapse navbar-collapse" id="navbarNavAltMarkup">
					<div class="navbar-nav mt-1 ml-auto">
						<div class="dropdown show">
							<a class="btn btn-light text-primary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
								Produtos
							</a>
							<div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
								<a class="dropdown-item" href="/cadastroProdutoAdmin">Cadastrar Produto</a>
								<div class="dropdown-divider"></div>
								<a class="dropdown-item" href="/listagemProdutoAdmin">Lista de Produtos</a>
							</div>
						</div>
					</div>
					<div class="navbar-nav mt-1 ml-1">
						<div class="dropdown show">
							<a class="btn btn-light text-primary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
								Usuarios
							</a>
							<div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
								<a class="dropdown-item" href="/cadastroUsuarioAdmin">Cadastrar Usuario</a>
								<div class="dropdown-divider"></div>
								<a class="dropdown-item" href="/listagemUsuarioAdmin">Lista de Usuarios</a>
								</div>
						</div>
					</div>
				</div>
			</div>
		</nav>
	</header>
	<br>
	<br>
	<br>

	<?= $this->content() ?>
</body>

</html>