<html>

<head>
	<meta charset="utf-8" />
	<title>Miniframework</title>

	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">

	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

	<link rel="stylesheet" type="text/css" href="/css/style.css">

</head>

<body>
	<header class="fixed-top">
		<nav class="navbar navbar-expand-lg bg-light">
			<div class="container-fluid">
				<a class="navbar-brand" href="/">
					<i class="fa fa-shopping-cart" aria-hidden="true"></i>
				</a>
				<div class="collapse navbar-collapse ml-2 mt-1" id="navbarNavAltMarkup">
					<form class="mt-2" action="">
						<span>Pesquise:</span>
						<input class="ml-1" type="text" name="" id="">
					</form>
					<div class="navbar-nav ml-3 mb-2">
						<a class="nav-link" href="/cadastroProduto">Cadastrar Produtos</a>
						<a class="nav-link" href="/cadastroUsuario">Cadastrar Usuarios</a>
					</div>
					<div class="navbar-nav ml-auto mb-2">
						<button type="button" class="btn btn-light text-primary">
						<i class="fa fa-shopping-cart" aria-hidden="true"></i>
							Carrinho	 
						<span class="badge badge-light">4</span>
						</button>
						<div class="dropdown show ml-2">
							<a class="btn btn-light text-primary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
								<? foreach($this->view->getUser as $key => $usuario) { ?>
									<? if($usuario['id'] != '') {?>
									<a class="dropdown-item" href="#"><?= $usuario['nome'] ?></a>
								<?}
								?>	
								<?} 
								?>
								
							</a>
							<div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
							<? foreach($this->view->getUser as $key => $usuario) { ?>
									<? if($usuario['id'] = '') {?>
									<a class="dropdown-item" href="#"><?= $usuario['nome'] ?></a>
								<?}
								?>	
								<?} 
								?>
							<a class="dropdown-item" href="/login">Entrar</a>
							<a class="dropdown-item" href="/sair">Sair</a>
							</div>
						</div>
					</div>
				</div>
			</div>
		</nav>
	</header>



	<?= $this->content() ?>
	<footer class="fixed-bottom mb-4">
		<hr style="background-color: black;">
		<div class="container">
			<div class="row text-center">
				<div class="col-md-4 box">
					<span class="copyright quick-links">Copyright &copy; Your Website <script>
							document.write(new Date().getFullYear())
						</script>
					</span>
				</div>
				<div class="col-md-4 box">
					<i class="fa fa-shopping-cart fa-3x" aria-hidden="true"></i>
				</div>
				<div class="col-md-4 box">
					<ul class="list-inline quick-links">
						<li class="list-inline-item">
							<span href="#">Endereço:</span>
							<span href="#">Rua Rio Grande do Sul N 385</span>
						</li>
					</ul>
				</div>
			</div>
		</div>
	</footer>
</body>

</html>