<script>
    $(document).ready(function () {
    getDataTable('#listagem-usuarios');
})

function getDataTable(id) {
    $(id).DataTable({
        "ordering": true,
        "paging": true,
        "searching": true,
        "oLanguage": {
            "sEmptyTable": "Nenhum registro encontrado na tabela",
            "sInfo": "Mostrar _START_ até _END_ de _TOTAL_ registros",
            "sInfoEmpty": "Mostrar 0 até 0 de 0 Registros",
            "sInfoFiltered": "(Filtrar de _MAX_ total registros)",
            "sInfoPostFix": "",
            "sInfoThousands": ".",
            "sLengthMenu": "Mostrar _MENU_ registros por pagina",
            "sLoadingRecords": "Carregando...",
            "sProcessing": "Processando...",
            "sZeroRecords": "Nenhum registro encontrado",
            "sSearch": "Pesquisar",
            "oPaginate": {
                "sNext": "Proximo",
                "sPrevious": "Anterior",
                "sFirst": "Primeiro",
                "sLast": "Ultimo"
            },
            "oAria": {
                "sSortAscending": ": Ordenar colunas de forma ascendente",
                "sSortDescending": ": Ordenar colunas de forma descendente"
            }
        }
    });
    $('.modal-button').click(function (e) {
        let text = e.target.id;
        let id = text.split("-");
        let nome = id[3];
        let 
    })
}
</script>
<table class="table mt-4" id="listagem-usuarios">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Email</th>
      <th scope="col">Nome</th>
      <th scope="col">Data de Criação</th>
      <th scope="col">Data de Alteração</th>
      <th scope="col">Ações</th>
    </tr>
  </thead>
  <tbody>
        <? foreach($this->view->getUsuarios as $usuario)  {?>
            <tr>
                <td scope="row"><?= $usuario['email']?></td>
                <td><?= $usuario['nome']?></td></td>
                <td><?= $usuario['data_criacao']?></td>
                <td><?= $usuario['data_alteracao']?></td>
                <td>
                    <a href="/editarUsuarioAdmin/<?=$usuario['id']?>" style="color: white;" class="btn btn-info btn-sm">Editar</a>
                    <button id="id-button-modal-<?= $usuario['nome']?>-<?=$usuario['id']?>"  style="color: white;" class="btn btn-danger btn-sm modal-button">Remover</button>
                </td>
            <?} 
            ?>
            </tr>
  </tbody>
</table>


<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div>Deseja remover o usuario? <?= $usuario['nome']?> </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Remover</button>
      </div>
    </div>
  </div>
</div>