<table class="table mt-4">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Email</th>
      <th scope="col">Nome</th>
      <th scope="col">Data de Criação</th>
      <th scope="col">Data de Alteração</th>
      <th scope="col">Ações</th>
    </tr>
  </thead>
  <tbody>
    <tr>
        <? foreach($this->view->getUsuarios as $usuario)  {?>
            <th scope="row"><?= $usuario['email']?></th>
            <td><?= $usuario['data']?></td></td>
            <td>Otto</td>
            <td>@mdo</td>
            <td>@mdo</td>
            <?} ?>
    </tr>
  </tbody>
</table>