<table class="table mt-4">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Email</th>
      <th scope="col">Nome</th>
      <th scope="col">Data de Criação</th>
      <th scope="col">Data de Alteração</th>
      <th scope="col">Ações</th>
    </tr>
  </thead>
  <tbody>
        <? foreach($this->view->getUsuarios as $usuario)  {?>
            <tr>
            <td scope="row"><?= $usuario['email']?></td>
            <td><?= $usuario['nome']?></td></td>
            <td><?= $usuario['data_criacao']?></td>
            <td><?= $usuario['data_alteracao']?></td>
            <td>@mdo</td>
            <?} 
            ?>
            </tr>
  </tbody>
</table>