<?php
$produtos = $this->view->getProdutos;
$usuario = $this->view->getUsuario;
$favorito = $this->view->getFavorito;
$produtosRecomendados = $this->view->getProdutosRecomendados;
include('modalCarrinho.phtml');
include('modalFavorito.phtml');
?>

<link href="https://netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="https://netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
<script src="/js/produto.js"></script>
<link rel="stylesheet" href="/css/login.css">

<br>
<br>
<br>
<div class="container mb-5 text-center  justify-content-center">
    <div class="row text-center">
        <div id="carouselExampleControls" class="carousel slide col-12 text-center" data-ride="carousel">
            <div class="carousel-inner">
                <div class="carousel-item active text-center">
                    <h1 style="font-family: Stencil Std, fantasy">Produtos Recomendados</h1>
                </div>
                <?php foreach ($this->view->getProdutosRecomendados as $produtoRecomendado) { ?>
                    <div class="carousel-item text-center">
                        <a href="/produto/<?= $produtoRecomendado['produto_id'] ?>">
                            <img height="200px" class="text-center" src="/img/<?= $produtoRecomendado['nome_imagem'] ?>">
                        </a>
                    </div>
                <?php } ?>
            </div>

            <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon bg-dark" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
                <span class="carousel-control-next-icon bg-dark" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
    </div>
</div>
<br>
<br>
<div class="container section-bg produto-container mt-5">
    <div class="row">
        <?php foreach ($produtos as $produto) { ?>
            <div class="col-sm-4 col-lg-4 col-md-4 p-5">
                <div class="caption  mb-3 d-flex justify-content-end mr-5">
                    <?php
                    $produtoId = $produto['id'];
                    $isInAllArrays = false;
                    foreach ($this->view->getFavorito as $array) {
                        if (in_array($produtoId, $array)) {
                            $isInAllArrays = true;
                            break;
                        }
                    }
                    if ($isInAllArrays) { ?>
                        <form action="/removerFavorito" method="post">
                            <input type="hidden" value="<?= $produtoId ?>" name="produtoId">
                            <button type="submit" class="btn btn-light">
                                <i class="fa fa-solid fa-heart fa-2x" style="color: #df2020;"></i>
                            </button>
                        </form>
                    <?php } else {
                    ?>
                        <form action="/adicionarFavorito" method="post">
                            <input type="hidden" value="<?= $produto['id'] ?>" name="produtoId">
                            <button type="submit" class="btn">
                                <i class="fa fa-regular fa-heart fa-2x" style="color: black;"></i>
                            </button>
                        </form>
                    <?php } ?>
                </div>
                <div class="caption">
                    <a href="/produto/<?= $produto['id'] ?>">
                        <img style="height: 40%;" class="img-fluid" src="data:image/png;base64,<?= $produto['produto_img'] ?>">
                    </a>
                </div>
                <div class="caption">
                    <h2 style="text-transform: capitalize" class="item-name text-left responsive-font-example">
                        <?= $produto['nome'] ?>
                    </h2>
                </div>
                <div class="caption">
                    <h4 class="item-name text-left responsive-font-example ">
                        <?= $produto['descricao'] ?>
                    </h4>
                </div>
                <?php if (isset($usuario['id'])) { ?>
                    <div class="caption">
                        <div class="input-group mb-3">
                            <button onclick="incrementQtd(<?= $produto['id'] ?>)" type="button" class="quantity-right-plus btn btn-info btn-number btn-sm ml-2" data-type="plus" data-field="">
                                <span class="glyphicon glyphicon-plus"></span>
                            </button>
                            <input style="width:34px;height:25px" type="text" id="quantity-<?= $produto['id'] ?>" name="quantity" class="form-control font-weight-bold" value="1" min="1" max="100">
                            <button onclick="decrementQtd(<?= $produto['id'] ?>)" type="button" class="quantity-left-minus btn btn-danger btn-number btn-sm ml-2" data-type="minus" data-field="">
                                <span class="glyphicon glyphicon-minus"></span>
                            </button>
                        </div>
                    </div>
                <?php } ?>
                <div class="caption d-flex justify-content-start mr-3">
                    <h4 style="font-family: Stencil Std, fantasy;font-size:17pt" class="item-price text-left mt-4 responsive-font-example font-weight-bold">
                        R$ <?= (number_format($produto['preco'], 2, ',', '')) ?>
                    </h4>
                    <?php if (isset($usuario['id'])) { ?>
                        <button onclick="adicionar(<?= $produto['id'] ?>)" class="btn btn-primary responsive-content btn-carrinho-home btn-sm btn-md ml-5 mt-3">Adicionar no carrinho</button>
                    <?php } ?>
                </div>
            </div>
        <?php } ?>
    </div>
</div>