<?php
$produtos = $this->view->getProdutos;
$usuario = $this->view->getUsuario;
$favorito = $this->view->getFavorito;
$produtosRecomendados = $this->view->getProdutosRecomendados;
include('modalCarrinho.phtml');
include('modalFavorito.phtml');
?>
<script async src="https://www.googletagmanager.com/gtag/js?id=G-64LCZHGWG4"></script>
<script>
    window.dataLayer = window.dataLayer || [];

    function gtag() {
        dataLayer.push(arguments);
    }
    gtag('js', new Date());

    gtag('config', 'G-64LCZHGWG4');
</script>
<link href="https://netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="https://netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
<script src="/js/produto.js"></script>
<link rel="stylesheet" href="/css/all.css">
<link rel="stylesheet" href="/css/carousel.css">

<br>
<div class="d-flex text-center justify-content-center">
    <h1 style="font-family:ippo, fantasy">Produtos Recomendados</h1>
</div>
<div class="container mb-5 text-center">
    <div class="row text-center">
        <div class="carousel-wrapper">
            <div class="carousel-container">
                <div class="carousel">
                    <?php foreach ($this->view->getProdutosRecomendados as $produtoRecomendado) { ?>
                        <div class="image-one">
                            <a href="/produto/<?= $produtoRecomendado['produto_id'] ?>">
                                <img height="200px" class="text-center" src="/img/<?= $produtoRecomendado['nome_imagem'] ?>">
                            </a>
                            <h3><?= $produtoRecomendado['produto_nome'] ?></h3>
                        </div>
                    <?php } ?>
                </div>
            </div>
        </div>
    </div>
</div>
<br>
<br>
<div class="container section-bg produto-container mt-5 mb-5">
    <div class="row">
        <?php foreach ($produtos as $produto) { ?>
            <div class="col-sm-4 col-lg-4 col-md-4 p-5 mb-5">
                <?php if (isset($usuario['id'])) { ?>
                    <div class="caption  mb-3 d-flex justify-content-end mr-5">
                        <?php
                        $produtoId = $produto['id'];
                        $isInAllArrays = false;
                        foreach ($this->view->getFavorito as $array) {
                            if (in_array($produtoId, $array)) {
                                $isInAllArrays = true;
                                break;
                            }
                        }
                        if ($isInAllArrays) { ?>
                            <form action="/removerFavorito" method="post">
                                <input type="hidden" value="<?= $produtoId ?>" name="produtoId">
                                <button type="submit" style="background-color:white;border:none">
                                    <i class="fa fa-solid fa-heart fa-2x" style="color:red;"></i>
                                </button>
                            </form>
                        <?php } else {
                        ?>
                            <form action="/adicionarFavorito" method="post">
                                <input type="hidden" value="<?= $produto['id'] ?>" name="produtoId">
                                <button type="submit" style="background-color:white;border:none">
                                    <i class="fa fa-heart-o fa-2x" style="color:red"></i>
                                </button>
                            </form>
                        <?php } ?>
                    </div>
                <?php } ?>
                <div class="caption">
                    <a href="/produto/<?= $produto['id'] ?>">
                        <img style="height: 20%;" class="img-fluid" src="/img/<?= $produto['produto_img_nome'] ?>">
                    </a>
                </div>
                <div class="caption">
                    <h2 style="text-transform: capitalize;font-size:17pt" class="item-name text-left ml-5">
                        <?= $produto['nome'] ?>
                    </h2>
                </div>
                <br>
                <div class="caption">
                    <h5 style="opacity: 50%;" class="item-name text-left responsive-font-example ">
                        <?= $produto['descricao'] ?>
                    </h5>
                </div>
                <?php if (isset($usuario['id'])) { ?>
                    <div class="caption mt-5 mr-5">
                        <div class="input-group mb-3">
                            <button onclick="incrementQtd(<?= $produto['id'] ?>)" type="button" class="quantity-right-plus btn btn-light text-dark btn-number btn-sm ml-2" data-type="plus" data-field="">
                                <i class="fas fa-plus"></i>
                            </button>
                            <input style="width:37px;height:25px" type="number" id="quantity-<?= $produto['id'] ?>" name="quantity" class="font-weight-bold text-center" value="1" min="1" max="100">
                            <button onclick="decrementQtd(<?= $produto['id'] ?>)" type="button" class="quantity-left-minus btn btn-light text-dark  btn-number btn-sm ml-2" id="botao-decremento-index" data-type="minus" data-field="">
                                <i class="fas fa-minus"></i>
                            </button>
                        </div>
                    </div>
                <?php } ?>
                <div class="caption d-flex justify-content-start mr-5">
                    <h4 style="font-family: Stencil Std, fantasy;font-size:17pt" class="item-price text-left mt-4 responsive-font-example font-weight-bold">
                        R$ <?= (number_format($produto['preco'], 2, ',', '')) ?>
                    </h4>
                    <?php if (isset($usuario['id'])) { ?>
                        <button onclick="adicionar(<?= $produto['id'] ?>)" class="btn btn-primary  btn-carrinho-home btn-sm btn-md ml-5 mt-3">Adicionar no carrinho</button>
                    <?php } ?>
                </div>
            </div>
        <?php } ?>
    </div>
</div>