<?php
$favoritoUsuario = $this->view->getFavorito;
?>
<?php if (!isset($this->view->isModalController)) { ?>
<script src="/js/produto.js"></script>
<?php } ?>

<?php if (!isset($this->view->isModalController)) { ?>
<div class="modal right fade" id="exampleModal3" role="dialog">
<?php } ?>
    <div class="modal-dialog">
        <div class="modal-content" style="overflow-x: hidden;">
            <div class="modal-header bg-light fixed-top">
                <button type="button" class="btn btn-danger ml-auto btn-sm" data-dismiss="modal">Fechar</button>
            </div>
            <br>
            <div class="modal-body mt-5 text-center">
                <h2 style="font-family: Stencil Std, fantasy;" class="text-center">Meus Favoritos</h2>
                <hr>
                    <div class="container text-center">
                        <div class="row d-flex flex-column text-center">
                                <?php foreach ($favoritoUsuario as $favorito) { ?>
                                    <div class="col-sm-4 col-lg-4 col-md-4 text-center ml-5">
                                        <div class="caption text-center">
                                            <img  style="height:150px" src="/img/<?= $favorito['produto_img_nome'] ?>">
                                        </div>
                                        <div class="caption text-center">
                                            <h3 style="text-transform: capitalize;font-family: Stencil Std, fantasy" class="item-name text-center  responsive-font-example">
                                                <?= $favorito['nome'] ?>
                                            </h3>
                                        </div>
                                    </div>
                                    <br>
                                <?php } ?>
                        </div>
                    </div>
            </div>
        </div>
    </div>
    <?php if (!isset($this->view->isModalController)) { ?>
</div>
<?php } ?>

<style>
    .modal.right.fade.in .modal-dialog {
        right: 0 !important;
        transform: translateX(-50%);
    }

    .modal.right .modal-content {
        height: 100%;
        overflow: auto;
        border-radius: 0;
    }

    .modal.right .modal-dialog {
        position: fixed;
        margin: auto;
        height: 100%;
        -webkit-transform: translate3d(0%, 0, 0);
        -ms-transform: translate3d(0%, 0, 0);
        -o-transform: translate3d(0%, 0, 0);
        transform: translate3d(0%, 0, 0);
    }

    .modal.right.fade.in .modal-dialog {
        transform: translateX(0%);
    }

    .modal.right.fade .modal-dialog {
        right: -320px;
        -webkit-transition: opacity 0.3s linear, right 0.3s ease-out;
        -moz-transition: opacity 0.3s linear, right 0.3s ease-out;
        -o-transition: opacity 0.3s linear, right 0.3s ease-out;
        transition: opacity 0.3s linear, right 0.3s ease-out;
    }


    .modal.right .modal-header {
        color: #fff
    }

    .modal.right .modal-header::after {
        content: "";
        display: inline-block;
    }

    .modal.right .close {
        text-shadow: none;
        opacity: 1;
        color: black;
        font-size: 26px
    }

    /*  form-control  */

    .form-control {
        border-radius: 0;
        box-shadow: none
    }

    .form-control:focus {
        box-shadow: none
    }


    /*  Button  */
</style>