<?php
$carrinhoUsuario = $this->view->getCarrinho;
$total = $this->view->getTotalCarrinho;

?>
<script src="/js/produto.js"></script>

<div class="modal right fade" id="exampleModal" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header bg-light fixed-top">
                <button type="button" class="btn btn-danger ml-auto btn-sm" data-dismiss="modal">Fechar</button>
            </div>
            <br>
            <br>
            <br>
            <div class="modal-body mt-5">
                <main id="cart" style="max-width:960px">
                    <div class="container-fluid">
                        <?php foreach ($carrinhoUsuario as $carrinho) { ?>
                            <?php if ($carrinho['status'] = 'ABERTO') { ?>
                                <div class="cartItem row">
                                    <div class="col-5 mt-5 d-flex flex-column">
                                        <img class="mt-2" style="height: 80px;width:180px" src="/img/<?= $carrinho['produto_img_nome'] ?>">
                                        <button style="width: 50px;" onclick="remover(<?= $carrinho['produto_id'] ?>,<?= $carrinho['usuario_id'] ?>)" id="id-button-carrinho-<?= $usuario['id'] ?>" class="btn btn-light btn-carrinho-usuario mt-4 ml-5">
                                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                                                <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z" />
                                                <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z" />
                                            </svg>
                                        </button>
                                    </div>
                                    <div class="col-7 d-flex flex-column flex-nowrap mt-4">
                                        <h3 class="item-name"><?= $carrinho['nome'] ?> </h3>
                                        <div class="caption mt-5">
                                            <div class="input-group mb-3">
                                                <button onclick="incrementQtdCarrinho(<?= $carrinho['produto_id'] ?>)" type="button" class="quantity-right-plus btn btn-light text-dark btn-number btn-sm " data-type="plus" data-field="">
                                                <i class="fas fa-plus"></i>
                                                </button>
                                                <input style="width:38px;height:25px" type="number" id="quantityCarrinho-<?= $carrinho['produto_id'] ?>" name="quantity" class="font-weight-bold text-center mt-1" value="<?= $carrinho['quantidade_produto'] ?>" min="1" max="100">
                                                <button onclick="decrementQtdCarrinho(<?= $carrinho['produto_id'] ?>)" type="button" class="quantity-left-minus btn btn-light text-dark btn-number btn-sm ml-1 " data-type="minus" data-field="">
                                                <i class="fas fa-minus"></i>
                                                </button>
                                            </div>
                                            <p class="text-left mt-2" style="font-family: Stencil Std, fantasy;font-size:17pt" id="cartItem1Price">R$ <?= (number_format($carrinho['preco'], 2, ',', '')) ?></p>
                                        </div>
                                    </div>
                                </div>
                                <hr>
                            <?php } ?>
                        <?php }
                        ?>
                    </div>
                </main>
                <div class="fixed-bottom bg-light ">
                    <div class="d-flex justify-content-center flex-row">
                        <h3 style="font-family: Stencil Std, fantasy" id="total">Total: R$ <?= $total['total_produto'] ?></h3>
                        <form action="/criarPedido" method="post">
                            <input type="hidden" name="produtoId" value="">
                            <button onclick="mandarRequest()" style="height: 40px;" type="submit" class="btn btn-success btn-finalizar-carrinho mt-3 ml-4">Finalizar compra</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>


<style>
    .modal.right.fade.in .modal-dialog {
        right: 0 !important;
        transform: translateX(-50%);
    }

    .modal.right .modal-content {
        height: 100%;
        overflow: auto;
        border-radius: 0;
    }

    .modal.right .modal-dialog {
        position: fixed;
        margin: auto;
        height: 100%;
        -webkit-transform: translate3d(0%, 0, 0);
        -ms-transform: translate3d(0%, 0, 0);
        -o-transform: translate3d(0%, 0, 0);
        transform: translate3d(0%, 0, 0);
    }

    .modal.right.fade.in .modal-dialog {
        transform: translateX(0%);
    }

    .modal.right.fade .modal-dialog {
        right: -320px;
        -webkit-transition: opacity 0.3s linear, right 0.3s ease-out;
        -moz-transition: opacity 0.3s linear, right 0.3s ease-out;
        -o-transition: opacity 0.3s linear, right 0.3s ease-out;
        transition: opacity 0.3s linear, right 0.3s ease-out;
    }


    .modal.right .modal-header {
        color: #fff
    }

    .modal.right .modal-header::after {
        content: "";
        display: inline-block;
    }

    .modal.right .close {
        text-shadow: none;
        opacity: 1;
        color: black;
        font-size: 26px
    }

    /*  form-control  */

    .form-control {
        border-radius: 0;
        box-shadow: none
    }

    .form-control:focus {
        box-shadow: none
    }


    /*  Button  */
</style>