<?php
$pedido = $this->view->getPedidoId;
include('modalFavorito.phtml');
?>
<link href="https://netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="https://netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
<script src="/js/produto.js"></script>

<script>
    $('.btn-carrinho').click(function() {
        $('#exampleModal').modal('show');
    })
</script>

<br>
<br>
<br>
<div class="container section-bg">
    <div class="row">
        <div class="col">
            <div class="d-flex justify-content-center align-items-center">
                <h1 style="font-family: Stencil Std, fantasy;">
                    Pedido <?= $pedido ?> Finalizado com sucesso!
                </h1>
                <a style="height: 40%;" href="/" class="btn btn-info ml-5 mt-3">Voltar para Home</a>
            </div>
        </div>
    </div>
</div>