<?php
$produto = $this->view->getProdutoId;
?>

<script>
    
    function adicionar(id) {
            $.ajax({
                url: 'inserirProdutoCarrinho',
                type: 'POST',
                data: {
                    idUsuario: id,

                },
                success: function(response) {
                    window.location.href = "/listagemUsuarioAdmin"
                    alert("Deletado com sucesso")
                },
                error: function(e){
                    window.location.href = "/listagemUsuarioAdmin"
                    alert("Ocorreu um erro")
                }
            })
}
$('.btn-carrinho').click(function (e) {
    let text = e.target.id;
    let idText = text.split("-");
    let id = idText[2];
    console.log(text);
})
</script>


<link href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>

<!------ Include the above in your HEAD tag ---------->


<br>
<br>
<br>
<div class="container-fluid m-5">
    <div class="row">
        <div class="col-6">
            <img src="http://placehold.it/266x266" alt="">
        </div>
        <div class="col-6">
            <div class="row d-flex flex-column">
                <div class="">
                    <h1><?= $produto['nome'] ?> </h1>
                </div>
                <div class="">
                    <h4><?= $produto['descricao'] ?> </h4>
                </div>
                <div class="mt-5 d-flex flex-row">
                    <h2><?= $produto['preco'] ?> R$ </h2>
                    <div class="ml-5" style="width: 40px;">
                        <span class="input-group-btn">
                            <button type="button" class="quantity-left-minus btn btn-danger btn-number" data-type="minus" data-field="">
                                <span class="glyphicon glyphicon-minus"></span>
                            </button>
                        </span>
                        <input type="text" id="quantity" name="quantity" class="form-control input-number" value="10" min="1" max="100">
                        <span class="input-group-btn">
                            <button type="button" class="quantity-right-plus btn btn-info btn-number" data-type="plus" data-field="">
                                <span class="glyphicon glyphicon-plus"></span>
                            </button>
                        </span>
                    </div>
                </div>
                <br>
            </div>
            <div>
                <button class="btn btn-primary">Adicionar no carrinho</button>
            </div>
        </div>
    </div>
</div>