<?php
$produto = $this->view->getProdutoId;
$usuario = $this->view->getUsuario;
?>
<link href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
<script src="/js/produto.js"></script>
<script>
    $('.btn-carrinho').click(function() {
        $('#exampleModal').modal('show');
    })
</script>


<br>
<br>
<br>
<div class="container-fluid m-5">
    <div class="row">
        <div id="carouselExampleControls" class="carousel slide col-6" data-ride="carousel">
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <img class="d-block img-fluid" src="data:image/png;base64,<?= $produto['produto_img'] ?>" alt="First slide">
                    <h5 class="text-center" style="font-size: 20pt;">Imagem Principal</h5>
                </div>
                <?php if (!empty($produto['produto_img_2'])) { ?>
                    <div class="carousel-item">
                        <img class="d-block img-fluid" src="data:image/png;base64,<?= $produto['produto_img_2'] ?>">
                    </div>
                <? } ?>
                <?php if (!empty($produto['produto_img_3'])) { ?>
                    <div class="carousel-item">
                        <img class="d-block img-fluid" src="data:image/png;base64,<?= $produto['produto_img_3'] ?>" >
                    </div>
                <? } ?>
                <?php if (!empty($produto['produto_img_4'])) { ?>
                    <div class="carousel-item">
                        <img class="d-block img-fluid" src="data:image/png;base64,<?= $produto['produto_img_4'] ?>">
                    </div>
                <? } ?>
            </div>
            <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon bg-dark" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
                <span class="carousel-control-next-icon bg-dark" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
        <div class="col-6">
            <div class="row d-flex flex-column">
                <div class="">
                    <h1><?= $produto['nome'] ?> </h1>
                </div>
                <div class="">
                    <h4><?= $produto['descricao'] ?> </h4>
                </div>
                <div class="mt-5 d-flex flex-row">
                    <h2><?= $produto['preco'] ?> R$ </h2>
                    <div class="ml-5" style="width: 40px;">
                        <span class="input-group-btn">
                            <button onclick="decrementQtd(<?= $produto['id'] ?>)" type="button" class="quantity-left-minus btn btn-danger btn-number" data-type="minus" data-field="">
                                <span class="glyphicon glyphicon-minus"></span>
                            </button>
                        </span>
                        <input type="text" id="quantity-<?= $produto['id'] ?>" name="quantity" class="form-control input-number" value="10" min="1" max="100">
                        <span class="input-group-btn">
                            <button onclick="incrementQtd(<?= $produto['id'] ?>)" type="button" class="quantity-right-plus btn btn-info btn-number" data-type="plus" data-field="">
                                <span class="glyphicon glyphicon-plus"></span>
                            </button>
                        </span>
                    </div>
                </div>
                <br>
            </div>
            <div>
                <button onclick="adicionar(<?= $produto['id'] ?>)" class="btn btn-primary btn-sm btn-carrinho">Adicionar no carrinho</button>
            </div>
        </div>
    </div>
</div>

<?php
include('modalCarrinho.phtml');
?>