<?php
$produtos = $this->view->produtos;
$usuario = $this->view->getUsuario;
?>

<link href="https://netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="https://netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
<script src="/js/produto.js"></script>

<script>
    $('.btn-carrinho').click(function() {
        $('#exampleModal').modal('show');
    })
</script>

<br>
<br>
<br>
<div class="container section-bg mt-5">
    <div class="col-md-9">
        <div class="row">
            <?php foreach ($produtos as $produto) { ?>
                <?php if (!empty($produto)) { ?>
                    <div class="col-sm-4 col-lg-4 col-md-4">
                        <a href="/produto/<?= $produto['id'] ?>">
                        <img class="d-block img-fluid" src="data:image/png;base64,<?= $produto['produto_img'] ?>" alt="First slide">
                        </a>
                        <div class="caption">
                            <h4 class="item-name text-left">
                                <?= $produto['nome'] ?>
                            </h4>
                        </div>
                        <div class="caption">
                            <h4 class="item-name text-left">
                                <?= $produto['descricao'] ?>
                            </h4>
                        </div>
                        <div class="caption">
                            <h4 class="item-price text-left mr-3">
                                <?= $produto['preco'] ?>
                            </h4>
                        </div>
                        <?php if (isset($usuario['id'])) { ?>
                            <div class="caption d-flex ">
                                <div>
                                    <button onclick="adicionar(<?= $produto['id'] ?>)" class="btn btn-primary btn-sm btn-carrinho">Adicionar no carrinho</button>
                                </div>
                                <div class="ml-5" style="width: 40px;">
                                    <span class="input-group-btn">
                                        <button onclick="incrementQtd(<?= $produto['id'] ?>)" type="button" class="quantity-right-plus btn btn-info btn-number" data-type="plus" data-field="">
                                            <span class="glyphicon glyphicon-plus"></span>
                                        </button>
                                    </span>
                                    <input type="text" id="quantity-<?= $produto['id'] ?>" name="quantity" class="form-control input-number" value="1" min="1" max="100">
                                    <span class="input-group-btn">
                                        <button onclick="decrementQtd(<?= $produto['id'] ?>)" type="button" class="quantity-left-minus btn btn-danger btn-number" data-type="minus" data-field="">
                                            <span class="glyphicon glyphicon-minus"></span>
                                        </button>
                                    </span>
                                </div>
                            </div>
                    </div>
                <?php } ?>
            <?php }
            ?>
            <?php if(empty($produto)) 
            {?>
                <div>
                    Não encontramos o item
                </div>
           <?php } 
           ?>
        <?php } 
        ?>
        </div>
    </div>
</div>

<?php
include('modalCarrinho.phtml');
?>