<?php
$errosLogin =  $this->view->errosLogin;
?>

<link href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<link rel="stylesheet" href="/css/all.css">


<?php if(!empty($errosLogin)) { ?>
    <?php foreach($errosLogin as $erro ) { ?>
        <div style="font-size: 15pt;" class="alert alert-danger text-center m-5" role="alert">
            <?= $erro?>
         </div>
    <?php }
    ?>
<?php } 
?>
<br>
<br>
<section id="login" class="mt-5">
    <div class="container">
    	<div class="row ">
    	    <div class="col-xs-12 produto-container">
        	    <div class="form-wrap text-center">
                <img src="/img/download.png" alt="" class="ml-5 text-center">
                    <form role="form" action="/autenticar" method="post" id="login-form" autocomplete="off">
                        <div class="form-group">
                            <label for="email" class="sr-only">Email</label>
                            <input type="text" name="email" id="email" class="form-control border border-dark" placeholder="somebody@example.com">
                        </div>
                        <div class="form-group">
                            <label for="key" class="sr-only">Senha</label>
                            <input type="password" name="senha" id="key" class="form-control" placeholder="Senha">
                        </div>
                        <input type="submit" id="btn-login" class="btn btn-info btn-custom btn-block" value="Logar">
                    </form>
                    <a href="/loginAdmin">Logue com o admin</a>
					<hr>
        	    </div>
    		</div>
            
    	</div>
    </div>
</section>