<?php
$usuario = $this->view->getUsuario;
$contador = $this->view->getContador;
?>
<html>

<head>
	<meta charset="utf-8" />
	<title>Miniframework</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<link rel="stylesheet" href="/css/media_query.css">
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" crossorigin="anonymous">
	<script src="/js/produto.js"></script>
	<script src="https://code.jquery.com/jquery-3.3.1.min.js" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</head>

<body>
	<header class="fixed-top header-container bg-light" style="height: 10%;">
		<nav class="navbar navbar-expand-lg">
			<div class="container-fluid ">
				<div class="navbar-nav d-flex justify-content-start mr-auto">
					<a class="navbar-brand" href="/">
						<i class="fa fa-shopping-cart fa-1x" aria-hidden="true"></i>
					</a>
				</div>
				<div id="barraPesquisar" class="navbar-nav mr-auto d-flex flex-nowrap">
					<form class="mt-2 d-flex flex-nowrap" action="/pesquisarProdutos">
						<span style="font-size:1.75rem">Pesquise:</span>
						<input style="font-size: 13pt;" class="ml-3" placeholder="Pesquise pelo nome ou descrição" type="text" name="pesquisa" id="pesquisar">
					</form>
				</div>
				<div class="navbar-nav mr-2">
					<button class="btn btn-light btn-favorito">
						<i class=" fa fa-solid fa-heart fa-2x"></i>
					</button>
				</div>
				<div class="navbar-nav d-flex flex-row ">
					<?php if (isset($usuario['id'])) { ?>
						<button style="font-size:2rem" type="button" class="btn btn-light text-primary btn-carrinho">
							<i class="fa fa-shopping-cart" aria-hidden="true"></i>
							Carrinho
							<span class="badge badge-light"><?= $contador ?></span>
						</button>
					<?php } ?>

					<?php if (isset($usuario['id'])) { ?>
						<div class="dropdown show ml-2">
							<a style="font-size:2rem" class="btn btn-light text-primary " href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><?= $usuario['nome'] ?></a>
							<div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
								<a style="font-size:1.75rem" class="dropdown-item" href="/sair">Sair</a>
							</div>
						</div>
					<?php }
					?>
					<?php if (!isset($usuario['id'])) { ?>
						<a style="font-size:1.75rem" class="btn btn-info" href="/login">Entrar</a>
					<?php }
					?>
				</div>
			</div>
		</nav>
	</header>
	<main style="padding-top:7em;padding-bottom:7em">
		<?= $this->content() ?>
	</main>
	<br>
	<br>
	<footer class="bg-light fixed-bottom">
		<hr style="background-color: black;">
		<div class="container">
			<div class="row text-center">
				<div class="col-md-4 box">
					<span class="copyright quick-links">Copyright &copy; Your Website <script>
							document.write(new Date().getFullYear())
						</script>
					</span>
				</div>
				<div class="col-md-4 box">
					<i class="fa fa-shopping-cart fa-3x" aria-hidden="true"></i>
				</div>
				<div class="col-md-4 box">
					<ul class="list-inline quick-links">
						<li class="list-inline-item">
							<span href="#">Endereço:</span>
							<span href="#">Rua Rio Grande do Sul N 385</span>
						</li>
					</ul>
				</div>
			</div>
		</div>
	</footer>
	<script src="/js/produto.js"></script>
</body>

</html>