<html>

<head>
	<meta charset="utf-8" />
	<title>Miniframework</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<link rel="stylesheet" href="https://cdn.datatables.net/1.13.4/css/jquery.dataTables.min.css">
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
	<script src="https://code.jquery.com/jquery-3.3.1.min.js" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
	<script src="https://cdn.datatables.net/1.13.4/js/jquery.dataTables.min.js"></script>
	<link rel="stylesheet" href="/css/all.css">
</head>

<body>
	<header class="fixed-top">
		<nav class="navbar navbar-expand-lg bg-light header-container">
			<div class="container-fluid">
				<div class="navbar-nav d-flex justify-content-start mr-auto">
					<div class="navbar-nav d-flex justify-content-start mr-auto text-center">
						<a href="/homeAdmin">
							<img style="height:60px;width:60px" src="/img/download.png" alt="">
						</a>
					</div>
				</div>
				<div class="d-flex header-admin">
					<div class="navbar-nav mt-1 ml-auto p-2">
						<a href="/listagemFavoritoAdmin"  href="">Favoritos</a>
					</div>
					<div class="navbar-nav mt-1 ml-1 p-2 text-primary">
						<a href="/listagemPedidoAdmin"  href="">Pedidos</a>
					</div>
					<div class="navbar-nav mt-1 ml-1 p-2 text-primary">
						<a href="/listagemProdutoRecomendadoAdmin" href="">Produto Recomendado</a>
					</div>
					<div class="navbar-nav mt-1 ml-1 p-2 text-primary">
						<a href="/listagemProdutoAdmin" href="">Produtos</a>
					</div>
					<div class="navbar-nav mt-1 ml-1 p-2 text-primary">
						<a href="/listagemUsuarioAdmin"  href="">Usuarios</a>
					</div>
				</div>
			</div>
			</div>
		</nav>
	</header>
	<br>
	<br>
	<br>
	<?= $this->content() ?>
	<footer class="bg-light fixed-bottom" style="height:100px">
		<hr style="background-color: black;">
		<div class="container ">
			<div class="row">
				<div class="col-md-4 box mt-4">
					<span class="copyright quick-links">Copyright &copy; Your Website
					</span>
				</div>
				<div class="col-md-4 box text-center">
					<img style="height:80px;width:80px" src="/img/download.png" alt="">
				</div>
				<div class="col-md-4 box mt-4">
					<ul class="list-inline quick-links">
						<li class="list-inline-item">
							<span href="#">Endereço:</span>
							<span href="#">Rua Rio Grande do Sul N 385</span>
						</li>
					</ul>
				</div>
			</div>
		</div>
	</footer>
</body>

</html>