<?php
$usuario = $this->view->getUsuario;
$contador = $this->view->getContador;
?>
<html>

<head>
	<meta charset="utf-8" />
	<link rel="stylesheet" href="/css/all.css">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<link rel="stylesheet" href="/css/media_query.css">
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" crossorigin="anonymous">
	<script async src="https://www.googletagmanager.com/gtag/js?id=G-64LCZHGWG4"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-64LCZHGWG4');
</script>
	<script src="/js/produto.js"></script>
	<script src="https://code.jquery.com/jquery-3.3.1.min.js" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
	<link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<link rel="stylesheet" href="/css/all.css">
</head>

<body>
	<header class="fixed-top bg-light" style="height: 10%;">
		<nav class="navbar navbar-expand-lg header-container">
			<div class="container-fluid">
				<div class="navbar-nav d-flex justify-content-start mr-auto">
					<a href="/">
					<img style="height:60px;width:60px"src="/img/download.png" alt="">
					</a>
				</div>
				<div class="navbar-nav mr-auto d-flex flex-nowrap ml-5">
					<form class="d-flex flex-nowrap mt-4" action="/pesquisarProdutos">
						<input class="rounded text-dark border border-dark text-center border-top-0 border-left-0 border-right-0" style="width:350px;height:30px"  placeholder="Pesquise pelo nome ou descrição" type="text" name="pesquisa" id="pesquisar">
					</form>
				</div>
				<?php if (isset($usuario['id'])) { ?>
				<div class="navbar-nav mr-2">
					<button style="border:none" class="btn-favorito">
					<i class="fa fa-solid fa-heart fa-2x" style="color:red;"></i>
					</button>
				</div>
				<?php } ?>
				<div class="navbar-nav d-flex flex-row ">
					<?php if (isset($usuario['id'])) { ?>
						<button style="font-size: 15pt;" type="button" class="btn btn-light text-primary btn-carrinho">
							<i class="fa fa-shopping-cart" aria-hidden="true"></i>
							Carrinho
							<span class="badge badge-light"><?= $contador ?></span>
						</button>
					<?php } ?>

					<?php if (isset($usuario['id'])) { ?>
						<div class="dropdown show ml-2">
							<a style="font-size: 15pt;" class="btn btn-light text-primary" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><?= $usuario['nome'] ?></a>
							<div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
								<a style="font-size: 15pt;" class="dropdown-item" href="/sair">Sair</a>
							</div>
						</div>
					<?php }
					?>
					<?php if (!isset($usuario['id'])) { ?>
						<a style="font-size: 15pt;" href="/login">Entrar</a>
					<?php }
					?>
				</div>
			</div>
		</nav>
	</header>
	<main style="padding-top:7em;padding-bottom:7em">
		<?= $this->content() ?>
	</main>
	<br>
	<br>
	<footer class="bg-light fixed-bottom" style="height:120px">
		<hr style="background-color: black;">
		<div class="container ">
			<div class="row">
				<div class="col-md-4 box mt-4">
					<span class="copyright quick-links">Copyright &copy; Your Website
					</span>
				</div>
				<div class="col-md-4 box text-center">
				<img style="height:80px;width:80px" src="/img/download.png" alt="">
				</div>
				<div class="col-md-4 box mt-4">
					<ul class="list-inline quick-links">
						<li class="list-inline-item">
							<span href="#">Endereço:</span>
							<span href="#">Rua Rio Grande do Sul N 385</span>
						</li>
					</ul>
				</div>
			</div>
		</div>
	</footer>
	<script src="/js/produto.js"></script>
</body>

</html>