<?php
$usuario = $this->view->getUsuario;
$contador = $this->view->getContador;
?>

<html>

<head>
	<meta charset="utf-8" />
	<title>Miniframework</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
	<script src="/js/produto.js"></script>
	<script src="https://code.jquery.com/jquery-3.3.1.min.js" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</head>

<body>
	<header class="fixed-top">
		<nav class="navbar navbar-expand-lg bg-light">
			<div class="container-fluid">
				<div class="navbar-nav d-flex justify-content-start mr-auto">
					<div class="navbar-nav d-flex justify-content-start mr-auto text-center">
						<a href="/">
						<img style="height:60px;width:60px" src="/img/download.png" alt="">
						</a>
					</div>
				</div>
				<div class="navbar-nav mr-auto d-flex flex-nowrap mt-4">
				<form class="d-flex flex-nowrap" action="/pesquisarProdutos">
						<input class="rounded text-dark border border-dark text-center border-top-0 border-left-0 border-right-0" style="width:350px;height:30px"  placeholder="Pesquise pelo nome ou descrição" type="text" name="pesquisa" id="pesquisar">
					</form>
				</div>
				<div class="navbar-nav">
					<?php if (isset($usuario['id'])) { ?>
						<div class="dropdown show ml-2">
							<a class="btn btn-light text-primary " href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><?= $usuario['nome'] ?></a>
							<div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
								<a class="dropdown-item" href="/sair">Sair</a>
							</div>
						</div>
					<?php }
					?>
					<?php if (!isset($usuario['id'])) { ?>
						<a class="btn btn-info" href="/login">Entrar</a>
					<?php }
					?>
				</div>
			</div>
		</nav>
	</header>
	<br>
	<?= $this->content() ?>
	<footer class="bg-light fixed-bottom" style="height:120px">
		<hr style="background-color: black;">
		<div class="container ">
			<div class="row">
				<div class="col-md-4 box mt-4">
					<span class="copyright quick-links">Copyright &copy; Your Website
					</span>
				</div>
				<div class="col-md-4 box text-center">
				<img style="height:80px;width:80px" src="/img/download.png" alt="">
				</div>
				<div class="col-md-4 box mt-4">
					<ul class="list-inline quick-links">
						<li class="list-inline-item">
							<span href="#">Endereço:</span>
							<span href="#">Rua Rio Grande do Sul N 385</span>
						</li>
					</ul>
				</div>
			</div>
		</div>
	</footer>
</body>

</html>